new volumectl, now in bash

diff --git a/scripts/volumectl b/scripts/volumectl
--- a/scripts/volumectl
+++ b/scripts/volumectl
@@ -1,82 +1,96 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-import argparse
-import subprocess
-import re
+set -euo pipefail
 
-targets = ["mic", "vol"]
+MICROPHONE="@DEFAULT_AUDIO_SOURCE@"
+SPEAKER="@DEFAULT_AUDIO_SINK@"
 
-def get_target(target):
-    if target == "mic":
-        return "@DEFAULT_AUDIO_SOURCE@"
-    else:
-        return "@DEFAULT_AUDIO_SINK@"
+Help() {
+  echo "Control the volume of the speaker and microphone."
+  echo
+  echo "Usage:"
+  echo "  $(basename "$0") (mic|vol) <command>"
+  echo "  $(basename "$0") --help"
+  echo
+  echo "Commands:"
+  echo "  get         print the current volume as a number between 0 and 100, is called by default if no command is provided"
+  echo "  set <val>   set the volume to the specified value (a number between 0 and 100)"
+  echo "  mute        toggle mute on the target"
+}
 
-class TargetChoice():
-    def __contains__(self, item):
-        return item in targets
-    def __iter__(self):
-        return targets.__iter__()
+GetVolume() {
+  local volume
+  volume=$(wpctl get-volume $TARGET | cut -d ' ' -f 2)
+  volume=$(echo "$volume" | awk '{pcts = $0 * 100; print pcts}' -)
+  echo "$volume"
+}
 
-class SetChoice():
-    index = 0
-    def __contains__(self, item):
-        if self.index == 0:
-            self.index += 1
-            return item in targets
-        else: 
-            return type(item) is str
+SetVolume() {
+  local target_vol
+  target_vol=$(echo "$1" | awk '{target = $0 - ($0 %5); print target/100}' -)
+  wpctl set-volume $TARGET "$target_vol" --limit 1
+}
 
-parser = argparse.ArgumentParser(
-	prog="volumectl",
-	description="Control the volume of the output / input of the computer"
-)
+PARSED="$(getopt --options=h --longoptions=help --name="$0" -- "$@")"
+eval set -- "$PARSED"
 
-parser.add_argument('-g', '--get', action="store", choices=TargetChoice(), help="get the volume of the specified target (value between 0 and 100)")
-parser.add_argument('-s', '--set', nargs=2, action="store", dest="set_vol", choices=SetChoice(), metavar=(f"{{{targets[0]},{targets[1]}}}", "VOL[%][+|-]"), help="set the volume of the target to the nearest inferior multiple of 5")
-parser.add_argument('-m', '--mute', action="store", choices=TargetChoice(), help="toggle mute for the target")
+while true; do
+  case "$1" in
+  -h | --help)
+    Help
+    exit 0
+    ;;
+  --)
+    shift 1
+    break
+    ;;
+  *)
+    echo "Programming error"
+    exit 3
+    ;;
+  esac
+done
 
-args = parser.parse_args()
+TARGET=
+case "${1:-}" in
+mic)
+  TARGET=$MICROPHONE
+  shift 1
+  ;;
+vol)
+  TARGET=$SPEAKER
+  shift 1
+  ;;
+"")
+  echo "Expected target, see --help for how to use command"
+  exit 1
+  ;;
+*)
+  echo "Unknown target '$1', see --help for more information"
+  exit 1
+  ;;
+esac
 
-def run_command(cmd):
-    """Return a float between 0 and 100"""
-    output = subprocess.run(cmd, stdout=subprocess.PIPE)
-    # extract all number (found on https://stackoverflow.com/a/29581287)
-    rr = re.findall(r"[-+]?[.]?[\d]+(?:,\d\d\d)*[\.]?\d*(?:[eE][-+]?\d+)?", output.stdout.decode("utf-8"))
-    if len(rr) > 0:
-        val = float(rr[0]) * 100
-        return val
-    else:
-        return 0.0
-
-
-def get_volume(target):
-    command = ["wpctl", "get-volume", target]
-    output = run_command(command)
-    print(f"{int(output)}")
-    return output
-
-def mute(target):
-    command = ["wpctl", "set-mute", target, "toggle"]
-    return run_command(command)
-
-def set_volume(target, vol):
-    command = ["wpctl", "set-volume", target, vol, "--limit", "1"]
-    run_command(command)
-    # set volume to nearest inferior multiple of 5
-    val = get_volume(target)
-    if int(val) % 5 != 0:
-        vol = int(val) - (val % 5)
-        vol = vol / 100
-        vol = str(vol)
-        set_volume(target, vol)
-
-if args.set_vol:
-    target = get_target(args.set_vol[0])
-    set_volume(target, args.set_vol[1])
-elif args.mute:
-    target = get_target(args.mute)
-    mute(target)
-else:
-    target = get_target(args.get)
-    get_volume(target)
+case "${1:-}" in
+'' | get)
+  GetVolume
+  exit 0
+  ;;
+set)
+  shift 1
+  if [[ -z "${1:-}" ]]; then
+    echo "Missing target value"
+    exit 1
+  fi
+  SetVolume "$1"
+  exit 0
+  ;;
+mute)
+  wpctl set-mute $TARGET toggle
+  exit 0
+  ;;
+*)
+  echo "Unknown command '$1', see --help for more information"
+  exit 1
+  ;;
+esac
